buildscript {
    dependencies {
        classpath files("src/teavmc-classpath/resources")
    }
}

plugins {
    id "java"
    id "eclipse"
    id "org.teavm" version "0.9.2"
}

sourcesSets {
    main {
        java {
            srcDirs(
                "src/main/java",
                "src/game/java",
                "src/protocol-game/java",
                "src/teavm/java"
            )
        }
    }
    eagler {
        java {
            srcDir 'src/main/java'
            srcDir 'src/game/java'
            srcDir 'src/protocol-game/java'
            srcDir 'src/lwjgl/java'
        }
    }
}

repositories {
    mavenCentral()
}
