name: Build NoneClient

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Make EPK
        run: chmod +x CompileEPK.sh && ./CompileEPK.sh

      - name: Build JavaScript
        run: chmod +x CompileJS.sh && ./CompileJS.sh

      - name: Make Offline Client
        run: chmod +x MakeOfflineDownload.sh && ./MakeOfflineDownload.sh

      - name: Upload NoneClient
        uses: actions/upload-artifact@v4
        with:
          name: NoneClient
          path: |
            javascript/*.html
            javascript/classes.js
            javascript/assets.epk
